# wp-ing2.yaml（Regional 静的IPを使う例）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ing2
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.regional-static-ip-name: wp-gclb-ip-reg
spec:
  ingressClassName: gce
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress
                port:
                  number: 80
