apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  selector:
    io.kompose.service: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306  # db コンテナの listen ポートに合わせる
  type: ClusterIP
