apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - secret.yaml

namespace: web-production

images:
  - name: wordpress
    newName: asia-northeast1-docker.pkg.dev/mfeed-web-production/mfeed-web-production-repo/wordpress
    newTag: stable

patches:
  - path: patch-deployment.yaml
  - path: patch-serviceaccount.yaml
  - path: patch-backendconfig.yaml
  - path: patch-ingress.yaml
  - path: patch-ingress-ipv6.yaml

commonLabels:
  app.kubernetes.io/environment: production