apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: "REPLACE_PRODUCTION_DB_PASSWORD"
  WORDPRESS_DB_HOST: "127.0.0.1:3306"