apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mfeed-wordpress-secrets
  namespace: web-production
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/mfeed-web-1/secrets/mfeed-wp-prod-db-host/versions/latest"
        path: "WORDPRESS_DB_HOST"
      - resourceName: "projects/mfeed-web-1/secrets/mfeed-wp-prod-db-name/versions/latest"
        path: "WORDPRESS_DB_NAME"
      - resourceName: "projects/mfeed-web-1/secrets/mfeed-wp-prod-db-user/versions/latest"
        path: "WORDPRESS_DB_USER"
      - resourceName: "projects/mfeed-web-1/secrets/mfeed-wp-prod-db-password/versions/latest"
        path: "WORDPRESS_DB_PASSWORD"