apiVersion: v1
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # /home → /home/ に統一
      location = /home {
        return 301 /home/;
      }

      # healthcheck
      location = /healthz {
        return 200;
      }


      # WordPress（/home/ 以下）
      location ^~ /home/ {
        proxy_pass http://wordpress:80/;   # 末尾 / で /home/ を剥がして渡す
        proxy_set_header Host $http_host;  # ★ ポート含むHostを維持
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
      }

      # それ以外は静的サイト
      location / {
        proxy_pass http://static:80;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: ingress
  name: ingress-cm0
