apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfeed-wp-content-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 5Gi