apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: ingress-nginx
  name: mfeed-web-policy
spec:
  healthCheck:
    port: 10254
    type: HTTP
    requestPath: /healthz
  cdn:
    enabled: false
#    enabled: true
#    cachePolicy:
#      includeHost: true
#      includeProtocol: true
#      includeQueryString: false
  securityPolicy:
    name: mfeed-web-policy