apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: ingress-nginx-2-mfeed-web-policy
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "mfeed-web-policy"}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx-2
    app.kubernetes.io/component: controller
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80