apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - service.yaml
  - secretproviderclass.yaml
  - ingress.yaml
  - ingress-ipv6.yaml
  - backendconfig.yaml

namespace: web-staging

images:
  - name: wordpress
    newName: asia-northeast1-docker.pkg.dev/mfeed-web-staging/mfeed-web-staging-repo/wordpress
    newTag: stable

patches:
  - path: patch-deployment.yaml
  - path: patch-serviceaccount.yaml
#  - path: patch-backendconfig.yaml
#  - path: patch-ingress.yaml
#  - path: patch-ingress-ipv6.yaml

commonLabels:
  app.kubernetes.io/environment: staging