apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: 'MY]H"y4}>7xhV^R6'
  WORDPRESS_DB_HOST: "127.0.0.1:3306"