apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mfeed-wordpress-secrets
  namespace: web-staging
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/mfeed-web-staging/secrets/mfeed-wp-stg-db-host/versions/latest"
        path: "WORDPRESS_DB_HOST"
      - resourceName: "projects/mfeed-web-staging/secrets/mfeed-wp-stg-db-name/versions/latest"
        path: "WORDPRESS_DB_NAME"
      - resourceName: "projects/mfeed-web-staging/secrets/mfeed-wp-stg-db-user/versions/latest"
        path: "WORDPRESS_DB_USER"
      - resourceName: "projects/mfeed-web-staging/secrets/mfeed-wp-stg-db-password/versions/latest"
        path: "WORDPRESS_DB_PASSWORD"